spring:
#  테스트
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#
  application:
    name: GreengramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://34.70.113.56:3306/greenfirst
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestgyb
    password: kzbczatbpdekyjkv
mybatis:
  mapper-locations: mapper/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger # Swagger page? redirect
    operations-sorter: method #alpha(default): url ?? ??, method: http-method ?? ??
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true # try it out ? ?? ? request duration(?? ????) ? ??? ???


file:
  directory: D:\2024-01\download\greenfirstproject

page:
  default-page : 1
  default-size : 10



---

spring:
  config:
    activate:
      on-profile: test

file:
  directory: D:\2024-01\download\greenfirstproject