spring:
#  테스트
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: ${ENV_PROFILE:default}
#
  application:
    name: GreengramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DEFAULT.DB.URL}
    username: ${DEFAULT.DB.USERNAME}
    password: ${DEFAULT.DB.PASSWORD}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE.CLIENT_ID}
            client-secret: ${GOOGLE.CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/api/user/social"
            scope:
              - email
          naver:
            client-id: ${NAVER.CLIENT_ID}
            client-secret: ${NAVER.CLIENT_SECRET}
            scope:
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http%3A%2F%2Flocalhost%3A8080%2Fapi%2Fuser%2Fsocial
          kakao:
            client-id: ${KAKAO.CLIENT_ID}
            client-secret:
            scope:
              - id
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/api/user/social
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
mybatis:
  mapper-locations: mapper/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger # Swagger page? redirect
    operations-sorter: method #alpha(default): url ?? ??, method: http-method ?? ??
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true # try it out ? ?? ? request duration(?? ????) ? ??? ???


file:
  directory: D:\Students\FirstProject\BackEnd\media\greengramver3\

page:
  default-page : 1
  default-size : 10

email:
  host: ${MAIL.HOST}
  port: ${MAIL.PORT}
  username: ${MAIL.USERNAME}
  password: ${MAIL.PASSWORD}

google:
  client:
    id: ${GOOGLE.CLIENT_ID}
    secret: ${GOOGLE.CLIENT_SECRET}
  redirect:
    uri: http://localhost:8080/api/auth/client-google-login
kakao:
  client:
    id: ${KAKAO.CLIENT_ID}
  redirect:
    uri: http://localhost:8080/api/auth/client-kakao-login
naver:
  client:
    id: ${NAVER.CLIENT_ID}
    secret: ${NAVER.CLIENT_SECRET}
  redirect:
    uri: http://localhost:8080/api/auth/client-naver-login

open-data:
    service-key: ${OPENDATA.SERVICE_KEY}




